## Settings
title: TEST
owner: "reha"
url: "https://rehayilmazlar.github.io"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: ""
github: "rehayilmazlar/rehayilmazlar"
# path to: css/, fonts/, img/ and js/
assets_path: "/" # i.e. "/assets"
statement: "Designed by rehayilmazlar, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
